import Head from "next/head"
import Link from "next/link"
import React from "react"
import styles from '../styles/Home.module.css'
import Display from "@/modules/dashboard/components/Display"


function Home() {
  return (
    // Add Error Boundary
    // Import dashboard components
    <div className={styles.container}>
      <Head>
        <title>Events Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href='/EcommerceAnalytics'>Ecommerce Page</Link>
        <Display />
      </main>
    </div>
  )
}

export default Home
